<?php

namespace App\Filament\Resources\Appointments\Pages;

use App\Filament\Resources\Appointments\AppointmentResource;
use Filament\Actions\CreateAction;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateAppointment extends CreateRecord
{
    protected static string $resource = AppointmentResource::class;

    protected  function handleRecordCreation(array $data): Model
    {
        // Allow multiple records creation if service will be longer than one hour
        $records = array();
        $hourIds = $data['fk_hour_id_create'];

        foreach($hourIds as $hourId) {
            $data['fk_hour_id'] = $hourId;
            $data['appointment_note'] = "";
            $records[] = parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
        }

        // Return first created appointment
        return $records[0];
    }
}
