<?php

namespace App\Filament\Resources\Dentists\Pages;

use App\Filament\Resources\Dentists\DentistResource;
use App\Models\Dentist;
use App\Services\Functions;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditDentist extends EditRecord
{
    protected static string $resource = DentistResource::class;

    public function __construct(
        protected Functions $functions = new Functions()
    ) { }

    protected function getHeaderActions(): array
    {
        return [
            DeleteAction::make(),
        ];
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {
        $order = $data['order'];
        $dentistId = $record['dentist_id'];

        $this->functions->updateOrderOfOtherRecords(Dentist::class, $order, $dentistId, 'dentist_id');

        return parent::handleRecordUpdate($record, $data); // TODO: Change the autogenerated stub
    }
}
