<?php

namespace App\Filament\Resources\Categories\Pages;

use App\Filament\Resources\Categories\CategoryResource;
use App\Models\Category;
use App\Services\Functions;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditCategory extends EditRecord
{
    protected static string $resource = CategoryResource::class;

    public function __construct(
        protected Functions $functions = new Functions()
    ) { }

    protected function getHeaderActions(): array
    {
        return [
            DeleteAction::make(),
        ];
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {
        $order = $data['order'];
        $categoryId = $record['category_id'];

        $this->functions->updateOrderOfOtherRecords(Category::class, $order, $categoryId, 'category_id');

        return parent::handleRecordUpdate($record, $data); // TODO: Change the autogenerated stub
    }
}
