<?php

namespace App\Filament\Resources\Availabilities\Pages;

use App\Filament\Resources\Availabilities\AvailabilityResource;
use App\Models\Appointment;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;
use SebastianBergmann\CodeCoverage\Report\Xml\Report;

class CreateAvailability extends CreateRecord
{
    protected static string $resource = AvailabilityResource::class;

    public function handleRecordCreation(array $data): Model
    {
        // Cancel all appointments that the dentist has in the new days off period
        $bookedAppointments = Appointment::where('fk_appointment_status_id', 1)
                                        ->where('appointment_date', '>=', $data['from_date'])
                                        ->where('appointment_date', '<=', $data['to_date'])
                                        ->where('fk_dentist_id', $data['fk_dentist_id'])
                                        ->get();
        if(!$bookedAppointments->isEmpty()){
            $bookedAppointments->each(function (Appointment $appointment) {
                $appointment->update(['fk_appointment_status_id' => 3]);
            });
        }

        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
